# Generated by Django on 2026-05-17
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_recipe_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='zona',
            field=models.CharField(blank=True, max_length=100, default=''),
            preserve_default=False,
        ),
    ]
