# Generated by Django 5.0.14 on 2026-05-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_zona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="recipes/"),
        ),
    ]
